name: CI

on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --no-build --configuration Release

  pack:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Determine version
        run: echo "::set-env name=VERSION::$(git describe --tags --dirty)"

      - name: Pack
        run: dotnet pack --output ./artifacts --configuration Release -p:Version=$VERSION

      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ./artifacts

  publish:
    runs-on: ubuntu-latest
    needs: pack
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifacts
          path: ./artifacts

      - name: Publish packages
        run: dotnet nuget push ./artifacts/*.nupkg --source nuget.org --api-key ${{ secrets.NUGET_TOKEN }}
